export const dummyDataList = [
    {
      phoneNumber: "+97430000000",
      descriptionArabic: "براون كافيه يفخر بحبوب القهوة المحمصة بعناية...",
      descriptionEng: "Brown Café prides ourselves in our deep roasted coffee beans...",
      discount: "19",
      endAt: "2026-12-25",
      img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/25/4d/21/91/yasmine-palace-doha-festival.jpg",
      isBestSeller: "Yes",
      isVenue: "Yes",
      latitude: "25.2510",
      longitude: "51.4699",
      nameArabic: "براون سبيشالتي كوفي",
      nameEng: "Brown Specialty",
      pin: "445284",
      selectedCategory: "Food and Drink",
      selectedCity: "Doha",
      selectedCountry: "Qatar",
      selectedVenue: "West Walk",
      startAt: "2024-12-25",
      status: "Yes",
      time: "2025-04-16T13:24:22Z"
    },
    {
      phoneNumber: "+97430000001",
      descriptionArabic: "استمتع بأفضل الأطباق الإيطالية التقليدية...",
      descriptionEng: "Enjoy the best traditional Italian dishes in the heart of Doha...",
      discount: "25",
      endAt: "2026-11-15",
      img: "https://www.timeoutdoha.com/cloud/timeoutdoha/2021/08/17/BLOUNGE-doha.jpg",
      isBestSeller: "No",
      isVenue: "Yes",
      latitude: "25.2801",
      longitude: "51.5200",
      nameArabic: "ريستورانتي إيطاليانو",
      nameEng: "Ristorante Italiano",
      pin: "445285",
      selectedCategory: "Food and Drink",
      selectedCity: "Doha",
      selectedCountry: "Qatar",
      selectedVenue: "City Center",
      startAt: "2024-11-01",
      status: "Yes",
      time: "2025-04-16T13:25:22Z"
    },
    {
      phoneNumber: "+97430000002",
      descriptionArabic: "صالون يقدم خدمات تجميل عالية الجودة بأسعار مناسبة...",
      descriptionEng: "Salon offering high-quality beauty services at affordable prices...",
      discount: "15",
      endAt: "2026-10-10",
      img: "https://www.timeoutdoha.com/cloud/timeoutdoha/2022/09/01/Lobito-De-Mar-at-Marsa-Malaz-Kempinski-The-Pearl-Doha-1.jpg",
      isBestSeller: "No",
      isVenue: "No",
      latitude: "25.2950",
      longitude: "51.5100",
      nameArabic: "صالون جلام ستايل",
      nameEng: "Glam Style Salon",
      pin: "445286",
      selectedCategory: "Salon",
      selectedCity: "Doha",
      selectedCountry: "Qatar",
      selectedVenue: "The Pearl",
      startAt: "2024-10-01",
      status: "Yes",
      time: "2025-04-16T13:26:22Z"
    },
    {
      phoneNumber: "+97430000003",
      descriptionArabic: "استمتع بتجربة سبا فاخرة ومريحة بعد يوم طويل...",
      descriptionEng: "Relax in luxury spa treatments after a long day...",
      discount: "30",
      endAt: "2026-09-20",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG6hPz1LoJjNmIAUVJ21ed2FVL2UoavhC9Qw&s",
      isBestSeller: "Yes",
      isVenue: "No",
      latitude: "25.3000",
      longitude: "51.5050",
      nameArabic: "سبا الرفاهية",
      nameEng: "Luxury Spa",
      pin: "445287",
      selectedCategory: "Spa",
      selectedCity: "Doha",
      selectedCountry: "Qatar",
      selectedVenue: "West Walk",
      startAt: "2024-09-10",
      status: "Yes",
      time: "2025-04-16T13:27:22Z"
    },
    {
      phoneNumber: "+97430000004",
      descriptionArabic: "مطعم عربي يقدم أشهى الأكلات التقليدية بنكهات مميزة...",
      descriptionEng: "Arabic restaurant serving delicious traditional dishes with a modern twist...",
      discount: "20",
      endAt: "2026-08-30",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTezffRh53ndUhVJ2TmkC06wEbX1X5skj3ZHw&s",
      isBestSeller: "No",
      isVenue: "Yes",
      latitude: "25.2650",
      longitude: "51.4800",
      nameArabic: "البيت العربي",
      nameEng: "Arabian House",
      pin: "445288",
      selectedCategory: "Food and Drink",
      selectedCity: "Doha",
      selectedCountry: "Qatar",
      selectedVenue: "Villaggio Mall",
      startAt: "2024-08-01",
      status: "Yes",
      time: "2025-04-16T13:28:22Z"
    }
  ];
  