import {StyleSheet} from 'react-native'
import { Colors } from '../../../Themes/Colors';
import { Fonts } from '../../../Themes/Fonts';

export const getStyles = (language: string) => StyleSheet.create({
  MainContainer: {
    backgroundColor: Colors.dargBg,
    padding: 10,
    paddingHorizontal: '5%',
    paddingTop: '16%',
    flexGrow: 1,
  },
  H_Logo: {
    width: 110,
    height: 110,
    alignSelf: 'center',
    marginTop: 50,
    marginBottom: 20,
  },
  Welcome_Txt: {
    fontSize: 20,
    fontFamily: Fonts.SF_Bold,
    color: Colors.White,
    lineHeight: 24,
    alignSelf: 'center',
  },
  SignUp_Txt: {
    fontSize: 16,
    color: Colors.Black2,
    fontFamily: Fonts.SF_Medium,
    alignSelf: 'center',
    lineHeight: 20,
  },
  InputContainer: {
    marginTop: '2%',
  },
  Input_Field: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 55,
    backgroundColor: Colors.White4,
    borderWidth: 1,
    borderColor: Colors.grey1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 14,
  },
  Active_Input_Field: {
    borderWidth: 2,
    borderColor: Colors.Green,
    backgroundColor: Colors.White,
  },
  PhoneInput_Field: {
    flexDirection: language === 'en' ? 'row' : 'row-reverse',
    alignItems: 'center',
    height: 60,
    backgroundColor: Colors.White4,
    borderWidth: 2,
    borderColor: Colors.grey1,
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 6,
    marginBottom: 14,
    zIndex: 10,
  },
  User_Input: {
    flex: 1,
    width: '100%',
    fontSize: 14,
    color: Colors.Black2,
    lineHeight: 18,
    textAlign: language === 'en' ? 'left' : 'right',
  },
  PhoneNumber_Input: {
    textAlign: language === 'en' ? 'left' : 'right',
    fontSize: 14,
    color: Colors.Black2,
    paddingHorizontal: '3%',
    borderLeftWidth: language === 'en' ? 1 : 0,
    borderRightWidth: language === 'en' ? 0 : 1,
    borderColor: Colors.Grey9,
    width: 200,
    height: 59,
  },
  Error: {
    marginVertical: 5,
    marginBottom: 15,
    fontSize: 12,
    fontWeight: 'bold',
    color: Colors.Red,
  },
});