const ImgPath='../assets/images/'
export const Splash=require(ImgPath+'Splash.png')
export const Westwalk=require(ImgPath+'westwalk.png')
export const West_Icon=require(ImgPath+'westwalk_Icon.png')
export const West_Logo=require(ImgPath+'westwalk_logo.png')
export const West_NB=require(ImgPath+'westwalk_NB.png')
export const West_NW=require(ImgPath+'westwalk_NW.png')
export const BackgroundImg=require(ImgPath+'image.png')
export const NoDataFound=require(ImgPath+'NodataFound.jpg')




const IconPath='../assets/icons/'
export const User=require(IconPath+'user.png')
export const P_IMG=require(IconPath+'pp.png')
export const Tenants=require(IconPath+'real-estate.png')
export const Emp_User=require(IconPath+'emp_user.png')
export const Hide=require(IconPath+'hide.png')
export const Show=require(IconPath+'show.png')
export const Lock=require(IconPath+'lock.png')
export const ManIcon=require(IconPath+'man.png')
export const Tick=require(IconPath+'Tick.png')
export const Email=require(IconPath+'email.png')
export const Language=require(IconPath+'language.png')
export const Scope=require(IconPath+'scope.png')
export const Back_Icon=require(IconPath+'Back.png')
export const Dark_Heart=require(IconPath+'green_heart.png')
export const Light_Heart=require(IconPath+'lightgreen_heart.png')
export const HomeIcon=require(IconPath+'home.png')
export const ProfileIcon=require(IconPath+'profile.png')
export const Wishlist=require(IconPath+'wishlist.png')
export const DocIcon=require(IconPath+'doc.png')
export const HistroyIcon=require(IconPath+'history.png')
export const DropDownIcon=require(IconPath+'dropdownIcon.png')
export const Error=require(IconPath+'error.png')
export const Success=require(IconPath+'success.png')
export const Info=require(IconPath+'info.png')
export const Warning=require(IconPath+'warning.png')
export const Contact_us=require(IconPath+'Contactus.png')
export const location=require(IconPath+'location.png')
export const Phone=require(IconPath+'telephone.png')