import {StyleSheet} from 'react-native';
import {Fonts} from '../../../Themes/Fonts';
export const AuthColors = {
  background: '#FFFFFF',
  green: '#005029',
  text: '#16392A',
  muted: '#78817C',
  border: '#DCE3DE',
  error: '#B42318',
};
export const getStyles = (language: string) =>
  StyleSheet.create({
    Root: {flex: 1, backgroundColor: AuthColors.background},
    Flex: {flex: 1},
    MainContainer: {flexGrow: 1, paddingHorizontal: 24, paddingBottom: 24},
    HeroBlock: {alignItems: 'center', paddingTop: 12, paddingBottom: 28, },
    H_Logo: {width: 100, height: 100, marginBottom: 10},
    Welcome_Txt: {
      fontFamily: Fonts.SF_Bold,
      fontSize: 30,
      lineHeight: 39,
      color: AuthColors.green,
      textAlign: 'center',
    },
    SignUp_Txt: {
      fontFamily: Fonts.SF_Medium,
      fontSize: 15,
      lineHeight: 23,
      color: AuthColors.muted,
      textAlign: 'center',
      marginTop: 8,
      maxWidth: 320,
    },
    InputContainer: {width: '100%'},
    Label: {
      fontSize: 14,
      color: AuthColors.text,
      fontFamily: Fonts.SF_Medium,
      marginBottom: 9,
      textAlign: language === 'ar' ? 'right' : 'left',
    },
    Input_Field: {
      flexDirection: language === 'ar' ? 'row-reverse' : 'row',
      alignItems: 'center',
      height: 58,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: AuthColors.border,
      borderRadius: 14,
      paddingHorizontal: 14,
      marginBottom: 14,
    },
    Field_Icon: {
      width: 18,
      height: 18,
      resizeMode: 'contain',
      marginRight: language === 'ar' ? 0 : 10,
      marginLeft: language === 'ar' ? 10 : 0,
      tintColor: AuthColors.green,
    },
    PhoneInput_Field: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 58,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: AuthColors.border,
      borderRadius: 14,
      paddingHorizontal: 6,
      zIndex: 10,
    },
    Active_Input_Field: {borderColor: AuthColors.green},
    User_Input: {
      flex: 1,
      minWidth: 0,
      height: 44,
      fontSize: 15,
      color: AuthColors.text,
      paddingVertical: 0,
      backgroundColor: 'transparent',
      textAlign: language === 'ar' ? 'right' : 'left',
    },
    PhoneNumber_Input: {
      flex: 1,
      minWidth: 0,
      height: 44,
      fontSize: 16,
      color: AuthColors.text,
      paddingVertical: 0,
      paddingHorizontal: 12,
      borderLeftWidth: 1,
      borderColor: AuthColors.border,
      backgroundColor: 'transparent',
      textAlign: 'left',
      writingDirection: 'ltr',
    },
    Hint: {
      fontSize: 12,
      lineHeight: 19,
      color: AuthColors.muted,
      marginTop: 10,
      textAlign: language === 'ar' ? 'right' : 'left',
    },
    ErrorSlot: {minHeight: 28, justifyContent: 'center'},
    Error: {
      fontSize: 12,
      lineHeight: 18,
      color: AuthColors.error,
      textAlign: language === 'ar' ? 'right' : 'left',
    },
    PrimaryButton: {
      height: 56,
      borderRadius: 14,
      backgroundColor: AuthColors.green,
      alignItems: 'center',
      justifyContent: 'center',
    },
    PrimaryText: {color: '#FFFFFF', fontSize: 16, fontFamily: Fonts.SF_Bold},
    Disabled: {opacity: 0.5},
    Link_Btn: {alignSelf: 'center', marginTop: 18, paddingVertical: 10},
    Link_Txt: {
      color: AuthColors.green,
      fontSize: 14,
      fontFamily: Fonts.SF_Medium,
      textAlign: 'center',
    },
    Footer: {marginTop: 'auto', paddingTop: 30},
    DividerRow: {flexDirection: 'row', alignItems: 'center', marginBottom: 18},
    DividerLine: {flex: 1, height: 1, backgroundColor: AuthColors.border},
    DividerTxt: {color: AuthColors.muted, fontSize: 12, marginHorizontal: 12},
    Partner_Btn: {
      height: 52,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: AuthColors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    Partner_Txt: {
      fontSize: 14,
      color: AuthColors.green,
      fontFamily: Fonts.SF_Medium,
    },
    Privacy: {
      textAlign: 'center',
      fontSize: 12,
      color: AuthColors.muted,
      marginTop: 22,
      lineHeight: 19,
    },
    CheckboxRow: {marginTop: 16},
    PhoneNumber: {
      fontFamily: Fonts.SF_Bold,
      fontSize: 17,
      color: AuthColors.green,
      textAlign: 'center',
      writingDirection: 'ltr',
      marginTop: 12,
    },
    CodeWrap: {height: 58, position: 'relative', marginTop: 22},
    CodeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      height: 58,
    },
    CodeCell: {
      flex: 1,
      marginHorizontal: 3,
      borderWidth: 1,
      borderColor: AuthColors.border,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
    },
    CodeActive: {borderColor: AuthColors.green, backgroundColor: '#F3FAF6'},
    CodeDigit: {
      fontFamily: Fonts.SF_Bold,
      fontSize: 23,
      color: AuthColors.text,
    },
    CodeNative: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: 58,
      opacity: 0.02,
      color: 'transparent',
      backgroundColor: 'transparent',
    },
    resendRow: {alignItems: 'center', marginTop: 20},
    resendHint: {fontSize: 13, color: AuthColors.muted},
    resendLink: {
      fontSize: 13,
      color: AuthColors.green,
      fontFamily: Fonts.SF_Medium,
    },
    resendLinkDisabled: {color: AuthColors.muted},
    Header: {
      height: 48,
      justifyContent: 'center',
      alignItems: language === 'ar' ? 'flex-end' : 'flex-start',
    },
    BackIcon: {
      width: 24,
      height: 24,
      tintColor: AuthColors.green,
      transform: [{scaleX: language === 'ar' ? -1 : 1}],
    },
  });
