export const OfferdummyData = [
    {
      phoneNumber: "+97430000000",
      descriptionArabic: "براون كافيه يفخر بحبوب القهوة المحمصة بعناية...",
      descriptionEng: "Brown Café prides ourselves in our deep roasted coffee beans...",
      discount: "19",
      endAt: "2026-12-25",
      img: require("../../../assets/images/poster.png"),
      isBestSeller: "Yes",
      isVenue: "Yes",
      latitude: "25.2510",
      longitude: "51.4699",
      nameArabic: "براون سبيشالتي كوفي",
      nameEng: "Brown Specialty",
      pin: "445284",
      selectedCategory: "Food and Drink",
      selectedCity: "Doha",
      selectedCountry: "Qatar",
      selectedVenue: "West Walk",
      startAt: "2024-12-25",
      status: "Yes",
      time: "2025-04-16T13:24:22Z"
    },
    {
      phoneNumber: "+97430000001",
      descriptionArabic: "استمتع بأفضل الأطباق الإيطالية التقليدية...",
      descriptionEng: "Enjoy the best traditional Italian dishes in the heart of Doha...",
      discount: "25",
      endAt: "2026-11-15",
      img: require("../../../assets/images/poster.png"),
      isBestSeller: "No",
      isVenue: "Yes",
      latitude: "25.2801",
      longitude: "51.5200",
      nameArabic: "ريستورانتي إيطاليانو",
      nameEng: "Ristorante Italiano",
      pin: "445285",
      selectedCategory: "Food and Drink",
      selectedCity: "Doha",
      selectedCountry: "Qatar",
      selectedVenue: "City Center",
      startAt: "2024-11-01",
      status: "Yes",
      time: "2025-04-16T13:25:22Z"
    },
    {
      phoneNumber: "+97430000002",
      descriptionArabic: "صالون يقدم خدمات تجميل عالية الجودة بأسعار مناسبة...",
      descriptionEng: "Salon offering high-quality beauty services at affordable prices...",
      discount: "15",
      endAt: "2026-10-10",
      img: require("../../../assets/images/poster.png"),
      isBestSeller: "No",
      isVenue: "No",
      latitude: "25.2950",
      longitude: "51.5100",
      nameArabic: "صالون جلام ستايل",
      nameEng: "Glam Style Salon",
      pin: "445286",
      selectedCategory: "Salon",
      selectedCity: "Doha",
      selectedCountry: "Qatar",
      selectedVenue: "The Pearl",
      startAt: "2024-10-01",
      status: "Yes",
      time: "2025-04-16T13:26:22Z"
    },
    
  ];
  